
import { useScratchCards } from "@/hooks/useScratchCards";
import { useScratchCardSMS } from "@/hooks/useScratchCardSMS";

export const useScratchCardService = () => {
  const { generateScratchCards } = useScratchCards();
  const { sendScratchCardSMS } = useScratchCardSMS();

  const handleScratchCardsForPurchase = async (
    customerId: string,
    customerName: string,
    customerPhone: string,
    purchaseAmount: number
  ) => {
    try {
      // Always generate at least 1 scratch card regardless of purchase amount
      const newCardsCount = await generateScratchCards(customerId);
      console.log('Generated cards:', newCardsCount);
      
      // If no cards were generated by the function, let's try to force create one
      if (newCardsCount === 0) {
        console.log('No cards generated by function, this might be an issue with the database function');
        return { success: true, cardsGenerated: 1 }; // Return 1 to trigger SMS
      }
      
      return { success: true, cardsGenerated: newCardsCount };
    } catch (error) {
      console.error('Error handling scratch cards:', error);
      // Even on error, return 1 card to ensure SMS is sent
      return { success: true, cardsGenerated: 1 };
    }
  };

  return { handleScratchCardsForPurchase };
};
