// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpzwlxpbhipnzizthftb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wendseHBiaGlwbnppenRoZnRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MjMzODgsImV4cCI6MjA2Mzk5OTM4OH0.Klf9GKJdykKVg5nTdUFbGHXNMtxrYU8fUn7MVWDA-mM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);